name: my-pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r tests/requirements.txt
      - run: python -m pytest tests/unit -v